server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: papercup-sales-backend
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/papercup_sales?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  
  # Redis配置 (可选)
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT配置
jwt:
  secret: papercup-sales-secret-key-2024-this-is-a-very-long-secret-key-for-jwt-hmac-sha-algorithm
  expiration: 86400000  # 24小时
  header: Authorization
  prefix: Bearer 

# 文件上传路径配置
file:
  upload:
    path: ./uploads/
    domain: http://localhost:8080/api/files/

# 日志配置
logging:
  level:
    com.papercup: debug
    org.springframework.security: debug
